<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>EtherBound.Bench</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherBound.Sim\EtherBound.Sim.csproj" />
    <ProjectReference Include="..\EtherBound.Host\EtherBound.Host.csproj" />
  </ItemGroup>

</Project>
