/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Game */
        post: operations["new_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game State */
        get: operations["game_state_api_game_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Menu */
        get: operations["menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorResponse */
        ActorResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Game Minute */
            game_minute: number;
        };
        /** MenuResponse */
        MenuResponse: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** Verbs */
            verbs: string[];
        };
        /** NewGameRequest */
        NewGameRequest: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** StateResponse */
        StateResponse: {
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** InputMessage */
        InputMessage: {
            /**
             * Type
             * @constant
             */
            type: "input";
            /** Sequence */
            sequence: number;
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** ClockMessage */
        ClockMessage: {
            /**
             * Type
             * @constant
             */
            type: "clock";
            /**
             * Paused
             * @default null
             */
            paused: boolean | null;
            /**
             * Speed
             * @default null
             */
            speed: (1 | 3 | 10) | null;
        };
        /** AckMessage */
        AckMessage: {
            /**
             * Type
             * @constant
             */
            type: "ack";
            /** Sequence */
            sequence: number;
            /** Accepted */
            accepted: boolean;
            /** Actor Id */
            actor_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** ErrorMessage */
        ErrorMessage: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** ActorSnapshot */
        ActorSnapshot: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            /**
             * Type
             * @constant
             */
            type: "snapshot";
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
        };
        /** TickMessage */
        TickMessage: {
            /**
             * Type
             * @constant
             */
            type: "tick";
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    new_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_state_api_game_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
        };
    };
    menu_api_menu_get: {
        parameters: {
            query: {
                x: number;
                y: number;
                z?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
