/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Game */
        post: operations["new_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game State */
        get: operations["game_state_api_game_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Materials */
        get: operations["materials_api_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** World Chunk */
        get: operations["world_chunk_api_world_chunk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Menu */
        get: operations["menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorResponse */
        ActorResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** H */
            h: number;
        };
        /** ChunkLevelResponse */
        ChunkLevelResponse: {
            /** Z */
            z: number;
            /** Floor H */
            floor_h: number[];
            /** Floor Mat */
            floor_mat: number[];
            /** Wall N */
            wall_n: number[];
            /** Wall W */
            wall_w: number[];
            /** Edge Flags */
            edge_flags: number[];
            /** Flags */
            flags: number[];
        };
        /** ChunkResponse */
        ChunkResponse: {
            /** Cx */
            cx: number;
            /** Cy */
            cy: number;
            /** Revision */
            revision: number;
            /** Ground H */
            ground_h: number[];
            /** Surface Mat */
            surface_mat: number[];
            /** Levels */
            levels: components["schemas"]["ChunkLevelResponse"][];
        };
        /** ClimbAction */
        ClimbAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "climb";
            target: components["schemas"]["TileTarget"];
        };
        /** DigAction */
        DigAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "dig";
            target: components["schemas"]["TileTarget"];
        };
        /** EventRecord */
        EventRecord: {
            /** Seq */
            seq: number;
            /** Game Minute */
            game_minute: number;
            /** Type */
            type: string;
            /** Actor Id */
            actor_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["EventRecord"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Game Minute */
            game_minute: number;
        };
        /** InspectAction */
        InspectAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "inspect";
            target: components["schemas"]["TileTarget"];
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Walkable */
            walkable: boolean;
            /** Walk Cost */
            walk_cost: number;
            /** Solid */
            solid: boolean;
            /** Blocks Sight */
            blocks_sight: boolean;
            /** Diggable */
            diggable: boolean;
            /** Dig Cost */
            dig_cost: number;
            /** Flammable */
            flammable: boolean;
            /** Density */
            density: number;
            /** Resistance */
            resistance: number;
            /** Liquid */
            liquid: boolean;
            /** Tags */
            tags: string[];
        };
        /** MenuEntry */
        MenuEntry: {
            /** Op */
            op: string;
            /** Label */
            label: string;
            /** Tags */
            tags: string[];
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Action */
            action: components["schemas"]["MoveAction"] | components["schemas"]["InspectAction"] | components["schemas"]["WaitAction"] | components["schemas"]["DigAction"] | components["schemas"]["ClimbAction"];
        };
        /** MenuResponse */
        MenuResponse: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** Target */
            target: string;
            /** Ops */
            ops: components["schemas"]["MenuEntry"][];
        };
        /** MoveAction */
        MoveAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** NewGameRequest */
        NewGameRequest: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** SelfTarget */
        SelfTarget: {
            /**
             * Kind
             * @default self
             * @constant
             */
            kind: "self";
        };
        /** StateResponse */
        StateResponse: {
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorResponse"][];
        };
        /** TileTarget */
        TileTarget: {
            /**
             * Kind
             * @default tile
             * @constant
             */
            kind: "tile";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaitAction */
        WaitAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "wait";
            target?: components["schemas"]["SelfTarget"];
        };
        /** InputMessage */
        InputMessage: {
            /**
             * Type
             * @constant
             */
            type: "input";
            /** Sequence */
            sequence: number;
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
            /**
             * Dt
             * @default 0.05
             */
            dt: number;
        };
        /** ClockMessage */
        ClockMessage: {
            /**
             * Type
             * @constant
             */
            type: "clock";
            /**
             * Paused
             * @default null
             */
            paused: boolean | null;
            /**
             * Speed
             * @default null
             */
            speed: (1 | 3 | 10) | null;
        };
        /** ActionMessage */
        ActionMessage: {
            /**
             * Type
             * @constant
             */
            type: "action";
            /** Sequence */
            sequence: number;
            /** Action */
            action: components["schemas"]["MoveAction"] | components["schemas"]["InspectAction"] | components["schemas"]["WaitAction"] | components["schemas"]["DigAction"] | components["schemas"]["ClimbAction"];
        };
        /** AckMessage */
        AckMessage: {
            /**
             * Type
             * @constant
             */
            type: "ack";
            /** Sequence */
            sequence: number;
            /** Accepted */
            accepted: boolean;
            /** Actor Id */
            actor_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * H
             * @default 0
             */
            h: number;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** ActivitySnapshot */
        ActivitySnapshot: {
            /** Op */
            op: string;
            /** Started Minute */
            started_minute: number;
            /** Ends Minute */
            ends_minute: number;
        };
        /** ResultMessage */
        ResultMessage: {
            /**
             * Type
             * @constant
             */
            type: "result";
            /** Sequence */
            sequence: number;
            /** Accepted */
            accepted: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Text
             * @default null
             */
            text: string | null;
            /** @default null */
            activity: components["schemas"]["ActivitySnapshot"] | null;
        };
        /** ActivityMessage */
        ActivityMessage: {
            /**
             * Type
             * @constant
             */
            type: "activity";
            /** Actor Id */
            actor_id: string;
            /** Op */
            op: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "completed" | "interrupted" | "failed";
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** ErrorMessage */
        ErrorMessage: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** ActorSnapshot */
        ActorSnapshot: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * H
             * @default 0
             */
            h: number;
            /** @default null */
            activity: components["schemas"]["ActivitySnapshot"] | null;
        };
        /** WorldInfo */
        WorldInfo: {
            /**
             * Chunk Size
             * @default 32
             */
            chunk_size: number;
            /**
             * Level H
             * @default 6
             */
            level_h: number;
            /** Bounds */
            bounds?: number[];
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            /**
             * Type
             * @constant
             */
            type: "snapshot";
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
            world?: components["schemas"]["WorldInfo"];
            /**
             * Gen Version
             * @default 0
             */
            gen_version: number;
        };
        /** TickMessage */
        TickMessage: {
            /**
             * Type
             * @constant
             */
            type: "tick";
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
            world?: components["schemas"]["WorldInfo"];
            /**
             * Gen Version
             * @default 0
             */
            gen_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    new_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_state_api_game_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
                type?: string | null;
                actor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    materials_api_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    world_chunk_api_world_chunk_get: {
        parameters: {
            query: {
                cx: number;
                cy: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    menu_api_menu_get: {
        parameters: {
            query: {
                x: number;
                y: number;
                z?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
