/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Game */
        post: operations["new_game_api_game_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generators */
        get: operations["generators_api_gen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game State */
        get: operations["game_state_api_game_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Materials */
        get: operations["materials_api_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** World Chunk */
        get: operations["world_chunk_api_world_chunk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Objects */
        get: operations["objects_api_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Menu */
        get: operations["menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorResponse */
        ActorResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** H */
            h: number;
        };
        /** ActorTarget */
        ActorTarget: {
            /**
             * Kind
             * @default actor
             * @constant
             */
            kind: "actor";
            /** Id */
            id: string;
        };
        /** BreakAction */
        BreakAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "break";
            /** Target */
            target: components["schemas"]["ObjectTarget"] | components["schemas"]["EdgeTarget"];
            /** @default null */
            tool: components["schemas"]["ObjectTarget"] | null;
        };
        /** ChunkLevelResponse */
        ChunkLevelResponse: {
            /** Z */
            z: number;
            /** Floor H */
            floor_h: number[];
            /** Floor Mat */
            floor_mat: number[];
            /** Wall N */
            wall_n: number[];
            /** Wall W */
            wall_w: number[];
            /** Edge Flags */
            edge_flags: number[];
            /** Flags */
            flags: number[];
        };
        /** ChunkResponse */
        ChunkResponse: {
            /** Cx */
            cx: number;
            /** Cy */
            cy: number;
            /** Revision */
            revision: number;
            /** Ground H */
            ground_h: number[];
            /** Surface Mat */
            surface_mat: number[];
            /** Levels */
            levels: components["schemas"]["ChunkLevelResponse"][];
            /** Objects */
            objects: components["schemas"]["ObjectResponse"][];
        };
        /** ClimbAction */
        ClimbAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "climb";
            target: components["schemas"]["TileTarget"];
        };
        /** CloseAction */
        CloseAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "close";
            target: components["schemas"]["ObjectTarget"];
        };
        /** DigAction */
        DigAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "dig";
            target: components["schemas"]["TileTarget"];
        };
        /** DragAction */
        DragAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "drag";
            /** Target */
            target: components["schemas"]["ObjectTarget"] | components["schemas"]["ActorTarget"];
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** DropAction */
        DropAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "drop";
            target: components["schemas"]["ObjectTarget"];
        };
        /** EdgeTarget */
        EdgeTarget: {
            /**
             * Kind
             * @default edge
             * @constant
             */
            kind: "edge";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "north" | "south" | "east" | "west";
        };
        /** EventRecord */
        EventRecord: {
            /** Seq */
            seq: number;
            /** Game Minute */
            game_minute: number;
            /** Type */
            type: string;
            /** Actor Id */
            actor_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["EventRecord"][];
        };
        /** GeneratorBayResponse */
        GeneratorBayResponse: {
            /** Key */
            key: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** GeneratorInfoResponse */
        GeneratorInfoResponse: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Fields */
            fields: components["schemas"]["OptionFieldResponse"][];
            /** Bays */
            bays: components["schemas"]["GeneratorBayResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Game Minute */
            game_minute: number;
        };
        /** HitAction */
        HitAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "hit";
            /** Target */
            target: components["schemas"]["ObjectTarget"] | components["schemas"]["ActorTarget"] | components["schemas"]["EdgeTarget"];
            /** @default null */
            tool: components["schemas"]["ObjectTarget"] | null;
        };
        /** InspectAction */
        InspectAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "inspect";
            /** Target */
            target: components["schemas"]["TileTarget"] | components["schemas"]["ObjectTarget"] | components["schemas"]["ActorTarget"];
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Walkable */
            walkable: boolean;
            /** Walk Cost */
            walk_cost: number;
            /** Solid */
            solid: boolean;
            /** Blocks Sight */
            blocks_sight: boolean;
            /** Diggable */
            diggable: boolean;
            /** Dig Cost */
            dig_cost: number;
            /** Flammable */
            flammable: boolean;
            /** Density */
            density: number;
            /** Resistance */
            resistance: number;
            /** Liquid */
            liquid: boolean;
            /** Tags */
            tags: string[];
        };
        /** MenuEntry */
        MenuEntry: {
            /** Op */
            op: string;
            /** Label */
            label: string;
            /** Tags */
            tags: string[];
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Subject */
            subject?: string | null;
            /** Action */
            action: components["schemas"]["MoveAction"] | components["schemas"]["InspectAction"] | components["schemas"]["WaitAction"] | components["schemas"]["DigAction"] | components["schemas"]["ClimbAction"] | components["schemas"]["TakeAction"] | components["schemas"]["DropAction"] | components["schemas"]["PutAction"] | components["schemas"]["OpenAction"] | components["schemas"]["CloseAction"] | components["schemas"]["WearAction"] | components["schemas"]["RemoveAction"] | components["schemas"]["PushAction"] | components["schemas"]["PullAction"] | components["schemas"]["DragAction"] | components["schemas"]["ThrowAction"] | components["schemas"]["HitAction"] | components["schemas"]["BreakAction"];
        };
        /** MenuResponse */
        MenuResponse: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** Target */
            target: string;
            /** Ops */
            ops: components["schemas"]["MenuEntry"][];
        };
        /** MoveAction */
        MoveAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** NewGameRequest */
        NewGameRequest: {
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /** Generator */
            generator?: string | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            /**
             * Paused
             * @default false
             */
            paused: boolean;
        };
        /** ObjectKindResponse */
        ObjectKindResponse: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Material */
            material: string;
            /** Mass */
            mass: number;
            /** Bulk */
            bulk: number;
            /** Height */
            height: number;
            /** Solid */
            solid: boolean;
            /** Surface */
            surface: boolean;
            /** Openable */
            openable: boolean;
            /** Container Capacity */
            container_capacity: number | null;
        };
        /** ObjectResponse */
        ObjectResponse: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
            /** Quantity */
            quantity: number;
            /** Open */
            open: boolean | null;
        };
        /** ObjectTarget */
        ObjectTarget: {
            /**
             * Kind
             * @default object
             * @constant
             */
            kind: "object";
            /** Id */
            id: number;
        };
        /** OpenAction */
        OpenAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "open";
            target: components["schemas"]["ObjectTarget"];
        };
        /** OptionFieldResponse */
        OptionFieldResponse: {
            /** Path */
            path: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Default */
            default: unknown;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Step */
            step: number | null;
            /** Choices */
            choices: string[];
            /** Group */
            group: string | null;
        };
        /** PullAction */
        PullAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "pull";
            /** Target */
            target: components["schemas"]["ObjectTarget"] | components["schemas"]["ActorTarget"];
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** PushAction */
        PushAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "push";
            /** Target */
            target: components["schemas"]["ObjectTarget"] | components["schemas"]["ActorTarget"];
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** PutAction */
        PutAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "put";
            target: components["schemas"]["ObjectTarget"];
            /** Into */
            into: components["schemas"]["ObjectTarget"] | components["schemas"]["TileTarget"];
        };
        /** RemoveAction */
        RemoveAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove";
            target: components["schemas"]["ObjectTarget"];
        };
        /** SelfTarget */
        SelfTarget: {
            /**
             * Kind
             * @default self
             * @constant
             */
            kind: "self";
        };
        /** StateResponse */
        StateResponse: {
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorResponse"][];
            /** Generator */
            generator: string;
            /** Gen Version */
            gen_version: number;
            /** Gen Options */
            gen_options: {
                [key: string]: unknown;
            };
        };
        /** TakeAction */
        TakeAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "take";
            target: components["schemas"]["ObjectTarget"];
        };
        /** ThrowAction */
        ThrowAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "throw";
            target: components["schemas"]["ObjectTarget"];
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** TileTarget */
        TileTarget: {
            /**
             * Kind
             * @default tile
             * @constant
             */
            kind: "tile";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaitAction */
        WaitAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "wait";
            target?: components["schemas"]["SelfTarget"];
        };
        /** WearAction */
        WearAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "wear";
            target: components["schemas"]["ObjectTarget"];
        };
        /** InputMessage */
        InputMessage: {
            /**
             * Type
             * @constant
             */
            type: "input";
            /** Sequence */
            sequence: number;
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
            /**
             * Dt
             * @default 0.05
             */
            dt: number;
        };
        /** ClockMessage */
        ClockMessage: {
            /**
             * Type
             * @constant
             */
            type: "clock";
            /**
             * Paused
             * @default null
             */
            paused: boolean | null;
            /**
             * Speed
             * @default null
             */
            speed: (1 | 3 | 10) | null;
        };
        /** ActionMessage */
        ActionMessage: {
            /**
             * Type
             * @constant
             */
            type: "action";
            /** Sequence */
            sequence: number;
            /** Action */
            action: components["schemas"]["MoveAction"] | components["schemas"]["InspectAction"] | components["schemas"]["WaitAction"] | components["schemas"]["DigAction"] | components["schemas"]["ClimbAction"] | components["schemas"]["TakeAction"] | components["schemas"]["DropAction"] | components["schemas"]["PutAction"] | components["schemas"]["OpenAction"] | components["schemas"]["CloseAction"] | components["schemas"]["WearAction"] | components["schemas"]["RemoveAction"] | components["schemas"]["PushAction"] | components["schemas"]["PullAction"] | components["schemas"]["DragAction"] | components["schemas"]["ThrowAction"] | components["schemas"]["HitAction"] | components["schemas"]["BreakAction"];
        };
        /** AckMessage */
        AckMessage: {
            /**
             * Type
             * @constant
             */
            type: "ack";
            /** Sequence */
            sequence: number;
            /** Accepted */
            accepted: boolean;
            /** Actor Id */
            actor_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * H
             * @default 0
             */
            h: number;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** ActivitySnapshot */
        ActivitySnapshot: {
            /** Op */
            op: string;
            /** Started Minute */
            started_minute: number;
            /** Ends Minute */
            ends_minute: number;
        };
        /** CarriedObject */
        CarriedObject: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Slot */
            slot: string;
        };
        /** PhysicsPosition */
        PhysicsPosition: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "actor" | "object";
            /** Id */
            id: string | number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
        };
        /** ResultMessage */
        ResultMessage: {
            /**
             * Type
             * @constant
             */
            type: "result";
            /** Sequence */
            sequence: number;
            /** Accepted */
            accepted: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /**
             * Text
             * @default null
             */
            text: string | null;
            /** @default null */
            activity: components["schemas"]["ActivitySnapshot"] | null;
            /** Carried */
            carried?: components["schemas"]["CarriedObject"][];
            /**
             * Load Kg
             * @default 0
             */
            load_kg: number;
            /** Trajectory */
            trajectory?: components["schemas"]["PhysicsPosition"][];
        };
        /** ActivityMessage */
        ActivityMessage: {
            /**
             * Type
             * @constant
             */
            type: "activity";
            /** Actor Id */
            actor_id: string;
            /** Op */
            op: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "completed" | "interrupted" | "failed";
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** ErrorMessage */
        ErrorMessage: {
            /**
             * Type
             * @constant
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** ActorSnapshot */
        ActorSnapshot: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Name
             * @default null
             */
            name: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /**
             * H
             * @default 0
             */
            h: number;
            /** @default null */
            activity: components["schemas"]["ActivitySnapshot"] | null;
            /** Carried */
            carried?: components["schemas"]["CarriedObject"][];
            /**
             * Load Kg
             * @default 0
             */
            load_kg: number;
        };
        /** WorldInfo */
        WorldInfo: {
            /**
             * Chunk Size
             * @default 32
             */
            chunk_size: number;
            /**
             * Level H
             * @default 6
             */
            level_h: number;
            /** Bounds */
            bounds?: number[];
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            /**
             * Type
             * @constant
             */
            type: "snapshot";
            /** Seed */
            seed: number;
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
            world?: components["schemas"]["WorldInfo"];
            /**
             * Gen Version
             * @default 0
             */
            gen_version: number;
        };
        /** TickMessage */
        TickMessage: {
            /**
             * Type
             * @constant
             */
            type: "tick";
            /** Game Minute */
            game_minute: number;
            /** Speed */
            speed: number;
            /** Paused */
            paused: boolean;
            /** Actors */
            actors: components["schemas"]["ActorSnapshot"][];
            world?: components["schemas"]["WorldInfo"];
            /**
             * Gen Version
             * @default 0
             */
            gen_version: number;
        };
        /** ChunkLevelMessage */
        ChunkLevelMessage: {
            /** Z */
            z: number;
            /** Floor H */
            floor_h: number[];
            /** Floor Mat */
            floor_mat: number[];
            /** Wall N */
            wall_n: number[];
            /** Wall W */
            wall_w: number[];
            /** Edge Flags */
            edge_flags: number[];
            /** Flags */
            flags: number[];
        };
        /** ObjectMessage */
        ObjectMessage: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
            /** Quantity */
            quantity: number;
            /**
             * Open
             * @default null
             */
            open: boolean | null;
        };
        /** ChunkMessage */
        ChunkMessage: {
            /**
             * Type
             * @constant
             */
            type: "chunk";
            /** Cx */
            cx: number;
            /** Cy */
            cy: number;
            /** Revision */
            revision: number;
            /** Ground H */
            ground_h: number[];
            /** Surface Mat */
            surface_mat: number[];
            /** Levels */
            levels: components["schemas"]["ChunkLevelMessage"][];
            /** Objects */
            objects?: components["schemas"]["ObjectMessage"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    new_game_api_game_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generators_api_gen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratorInfoResponse"][];
                };
            };
        };
    };
    game_state_api_game_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
                type?: string | null;
                actor_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    materials_api_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    world_chunk_api_world_chunk_get: {
        parameters: {
            query: {
                cx: number;
                cy: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    objects_api_objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectKindResponse"][];
                };
            };
        };
    };
    menu_api_menu_get: {
        parameters: {
            query: {
                x: number;
                y: number;
                z?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
